{"name":"Tryjs","tagline":"","body":"tryjs\r\n=====\r\n\r\n> window.onerror在webkit中对于跨域的脚本错误无法捕获其stack，经常让我们无法定位上报的问题，tryjs利用try-catch将函数包裹起来，让错误捕获变得容易。\r\n\r\n原理\r\n----\r\n\r\n对于基于AMD和jQuery的网站，几乎所有业务函数都是通过回调异步触发的，所以我们只需要将所有异步函数包裹起来就可以捕获到大部分错误。\r\n\r\n例如，对于require函数，一般是这样使用的：\r\n\r\n```javascript\r\nrequire(['./main'],\r\n\t// 想办法把这个函数包裹起来 \r\n\tfunction (main) {\r\n\t\t// 实际上这里才是在调用\r\n\t\tmain.init();\r\n\t});\r\n```\r\n\r\n类似的对于setTimeout函数，一般可以这样：\r\n\r\n```javascript\r\nsetTimeout(\r\n\t// 想办法把这个函数包裹起来就行了\r\n\tfunction () {\r\n\t\tdosomthing();\r\n\t}, \r\n\t1000\r\n);\r\n```\r\n\r\n包裹了什么？\r\n---------\r\n\r\n* setTimeout\r\n* setInterval\r\n* jQuery event add\r\n* jQuery ajax\r\n* require & define","google":"","note":"Don't delete this file! It's used internally to help with page regeneration."}